### ISSUE TITLE
Error while building TensorFlow

### ISSUE THREAD

**Issue by MrSlayer02** [samjabrahams/tensorflow-on-raspberry-pi#20] opened 2016-06-10 16:41 UTC
I'm trying to build  `TensorFlow`, but I get an error and I didn't find anything related to this. 
The error log : http://pastebin.com/zUfP4xsP

Any help ?

**Comment by samjabrahams** [comment] 2016-06-10 18:51
Thanks for opening this up- usually, exit status 1 or 4 indicates some sort of out of memory error.

Just to get started, could you confirm that you've installed some sort of USB (or other) memory drive as swap space? If so, what size is it? Additionally, could you use the `top` command to make sure that the swap is actually being recognized by the device?

**Comment by MrSlayer02** [comment] 2016-06-12 15:49
Yes, I installed a memory drive of 4GB. I will only be able to access my device tomorrow, I'll check if the swap is recognized and edit this tomorrow. Thanks for your help.

**Comment by MrSlayer02** [comment] 2016-06-13 13:30
I could fix this by editing some source code, it was caused by Eigen imports, but the main problem is `TensorFlow 0.9`, because you can't really disable GPU support, it requires CUDA for half floats even if you disabled GPU support in config. I'll downgrade to 0.8 for now, and wait for a fix to use 0.9.

**Comment by samjabrahams** [comment] 2016-06-13 22:47
Thanks for the info @MrSlayer02 - I'm going to leave this open until there is a documented way to work through this.

**Comment by MrSlayer02** [comment] 2016-06-14 07:34
I opened `an issue on TensorFlow's git`(https://github.com/tensorflow/tensorflow/issues/2829) , maybe this will be fixed soon ...

**Comment by samjabrahams** [comment] 2016-06-16 17:45
I'll add a note in `GUIDE.md` indicating that there is currently an issue with more recent commits and that the most recent confirmed compilation was at tag `r0.8`.

**Comment by samjabrahams** [comment] 2016-06-16 23:00
It looks like the issue has to do with the Neon instruction flag- the Eigen 16-bit floating point doesn't play nice with Neon, it would seem.

If you still want to build it yourself, try again without the `--copt="-mfpu=neon"` flag. If you just want 0.9rc0, I'm uploading the binary now!

**Comment by samjabrahams** [comment] 2016-06-16 23:22
If you still plan on building from scratch, let me know if you can confirm that removing the `-mfpu=neon` flag works for you, and I'll close this issue.

**Comment by MrSlayer02** [comment] 2016-06-17 08:44
Thanks for the pre-release :) 
I won't have time to try this out, actually I did this for a school project that ends today and finally TensorFlow 0.8, which I could build, was enough. I think you can close this.

**Closed** 2016-06-17 08:49 UTC
